[2024-05-10T00:00:32.330+0000] {processor.py:161} INFO - Started process (PID=25000) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py
[2024-05-10T00:00:32.333+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py for tasks to queue
[2024-05-10T00:00:32.340+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:00:32.340+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py
[2024-05-10T00:00:32.373+0000] {processor.py:840} INFO - DAG(s) 'consume_1_or_both_2_and_3_with_dataset_expressions', 'consume_1_or_2_with_dataset_expressions', 'dataset_consumes_unknown_never_scheduled', 'dataset_consumes_1_never_scheduled', 'dataset_consumes_1', 'dataset_consumes_1_and_2', 'dataset_produces_2', 'conditional_dataset_and_time_based_timetable', 'dataset_produces_1', 'consume_1_and_2_with_dataset_expressions' retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py
[2024-05-10T00:00:32.462+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:00:32.462+0000] {dag.py:3096} INFO - Sync 10 DAGs
[2024-05-10T00:00:32.509+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:00:32.508+0000] {dag.py:3954} INFO - Setting next_dagrun for conditional_dataset_and_time_based_timetable to 2024-05-08 01:00:00+00:00, run_after=2024-05-08 01:00:00+00:00
[2024-05-10T00:00:32.518+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:00:32.518+0000] {dag.py:3954} INFO - Setting next_dagrun for consume_1_and_2_with_dataset_expressions to None, run_after=None
[2024-05-10T00:00:32.524+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:00:32.524+0000] {dag.py:3954} INFO - Setting next_dagrun for consume_1_or_2_with_dataset_expressions to None, run_after=None
[2024-05-10T00:00:32.529+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:00:32.528+0000] {dag.py:3954} INFO - Setting next_dagrun for consume_1_or_both_2_and_3_with_dataset_expressions to None, run_after=None
[2024-05-10T00:00:32.535+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:00:32.535+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_consumes_1 to None, run_after=None
[2024-05-10T00:00:32.541+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:00:32.540+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_consumes_1_and_2 to None, run_after=None
[2024-05-10T00:00:32.548+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:00:32.547+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_consumes_1_never_scheduled to None, run_after=None
[2024-05-10T00:00:32.556+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:00:32.555+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_consumes_unknown_never_scheduled to None, run_after=None
[2024-05-10T00:00:32.564+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:00:32.564+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_produces_1 to 2024-05-09 00:00:00+00:00, run_after=2024-05-10 00:00:00+00:00
[2024-05-10T00:00:32.571+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:00:32.571+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_produces_2 to None, run_after=None
[2024-05-10T00:00:32.640+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py took 0.318 seconds
[2024-05-10T00:01:03.364+0000] {processor.py:161} INFO - Started process (PID=25058) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py
[2024-05-10T00:01:03.371+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py for tasks to queue
[2024-05-10T00:01:03.378+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:01:03.377+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py
[2024-05-10T00:01:03.407+0000] {processor.py:840} INFO - DAG(s) 'consume_1_or_both_2_and_3_with_dataset_expressions', 'conditional_dataset_and_time_based_timetable', 'dataset_consumes_1_never_scheduled', 'dataset_consumes_unknown_never_scheduled', 'dataset_produces_1', 'consume_1_and_2_with_dataset_expressions', 'consume_1_or_2_with_dataset_expressions', 'dataset_consumes_1_and_2', 'dataset_consumes_1', 'dataset_produces_2' retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py
[2024-05-10T00:01:03.512+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:01:03.511+0000] {dag.py:3096} INFO - Sync 10 DAGs
[2024-05-10T00:01:03.557+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:01:03.556+0000] {dag.py:3954} INFO - Setting next_dagrun for conditional_dataset_and_time_based_timetable to 2024-05-08 01:00:00+00:00, run_after=2024-05-08 01:00:00+00:00
[2024-05-10T00:01:03.574+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:01:03.574+0000] {dag.py:3954} INFO - Setting next_dagrun for consume_1_and_2_with_dataset_expressions to None, run_after=None
[2024-05-10T00:01:03.580+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:01:03.580+0000] {dag.py:3954} INFO - Setting next_dagrun for consume_1_or_2_with_dataset_expressions to None, run_after=None
[2024-05-10T00:01:03.586+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:01:03.586+0000] {dag.py:3954} INFO - Setting next_dagrun for consume_1_or_both_2_and_3_with_dataset_expressions to None, run_after=None
[2024-05-10T00:01:03.592+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:01:03.592+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_consumes_1 to None, run_after=None
[2024-05-10T00:01:03.596+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:01:03.596+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_consumes_1_and_2 to None, run_after=None
[2024-05-10T00:01:03.600+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:01:03.600+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_consumes_1_never_scheduled to None, run_after=None
[2024-05-10T00:01:03.604+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:01:03.604+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_consumes_unknown_never_scheduled to None, run_after=None
[2024-05-10T00:01:03.611+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:01:03.610+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_produces_1 to 2024-05-09 00:00:00+00:00, run_after=2024-05-10 00:00:00+00:00
[2024-05-10T00:01:03.615+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:01:03.614+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_produces_2 to None, run_after=None
[2024-05-10T00:01:03.662+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py took 0.310 seconds
[2024-05-10T00:01:34.260+0000] {processor.py:161} INFO - Started process (PID=25116) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py
[2024-05-10T00:01:34.264+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py for tasks to queue
[2024-05-10T00:01:34.267+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:01:34.267+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py
[2024-05-10T00:01:34.284+0000] {processor.py:840} INFO - DAG(s) 'consume_1_and_2_with_dataset_expressions', 'dataset_consumes_unknown_never_scheduled', 'consume_1_or_both_2_and_3_with_dataset_expressions', 'dataset_produces_2', 'dataset_consumes_1_never_scheduled', 'dataset_consumes_1', 'conditional_dataset_and_time_based_timetable', 'dataset_consumes_1_and_2', 'dataset_produces_1', 'consume_1_or_2_with_dataset_expressions' retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py
[2024-05-10T00:01:34.331+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:01:34.330+0000] {dag.py:3096} INFO - Sync 10 DAGs
[2024-05-10T00:01:34.365+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:01:34.365+0000] {dag.py:3954} INFO - Setting next_dagrun for conditional_dataset_and_time_based_timetable to 2024-05-08 01:00:00+00:00, run_after=2024-05-08 01:00:00+00:00
[2024-05-10T00:01:34.371+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:01:34.370+0000] {dag.py:3954} INFO - Setting next_dagrun for consume_1_and_2_with_dataset_expressions to None, run_after=None
[2024-05-10T00:01:34.375+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:01:34.374+0000] {dag.py:3954} INFO - Setting next_dagrun for consume_1_or_2_with_dataset_expressions to None, run_after=None
[2024-05-10T00:01:34.378+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:01:34.378+0000] {dag.py:3954} INFO - Setting next_dagrun for consume_1_or_both_2_and_3_with_dataset_expressions to None, run_after=None
[2024-05-10T00:01:34.381+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:01:34.381+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_consumes_1 to None, run_after=None
[2024-05-10T00:01:34.385+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:01:34.385+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_consumes_1_and_2 to None, run_after=None
[2024-05-10T00:01:34.388+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:01:34.388+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_consumes_1_never_scheduled to None, run_after=None
[2024-05-10T00:01:34.391+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:01:34.391+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_consumes_unknown_never_scheduled to None, run_after=None
[2024-05-10T00:01:34.396+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:01:34.396+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_produces_1 to 2024-05-09 00:00:00+00:00, run_after=2024-05-10 00:00:00+00:00
[2024-05-10T00:01:34.400+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:01:34.399+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_produces_2 to None, run_after=None
[2024-05-10T00:01:34.437+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py took 0.184 seconds
[2024-05-10T00:02:09.014+0000] {processor.py:161} INFO - Started process (PID=25173) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py
[2024-05-10T00:02:09.019+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py for tasks to queue
[2024-05-10T00:02:09.028+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:02:09.027+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py
[2024-05-10T00:02:09.069+0000] {processor.py:840} INFO - DAG(s) 'dataset_consumes_unknown_never_scheduled', 'consume_1_and_2_with_dataset_expressions', 'dataset_consumes_1_and_2', 'dataset_produces_2', 'dataset_produces_1', 'dataset_consumes_1', 'conditional_dataset_and_time_based_timetable', 'consume_1_or_both_2_and_3_with_dataset_expressions', 'consume_1_or_2_with_dataset_expressions', 'dataset_consumes_1_never_scheduled' retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py
[2024-05-10T00:02:09.165+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:02:09.164+0000] {dag.py:3096} INFO - Sync 10 DAGs
[2024-05-10T00:02:09.244+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:02:09.243+0000] {dag.py:3954} INFO - Setting next_dagrun for conditional_dataset_and_time_based_timetable to 2024-05-08 01:00:00+00:00, run_after=2024-05-08 01:00:00+00:00
[2024-05-10T00:02:09.263+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:02:09.262+0000] {dag.py:3954} INFO - Setting next_dagrun for consume_1_and_2_with_dataset_expressions to None, run_after=None
[2024-05-10T00:02:09.274+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:02:09.273+0000] {dag.py:3954} INFO - Setting next_dagrun for consume_1_or_2_with_dataset_expressions to None, run_after=None
[2024-05-10T00:02:09.285+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:02:09.285+0000] {dag.py:3954} INFO - Setting next_dagrun for consume_1_or_both_2_and_3_with_dataset_expressions to None, run_after=None
[2024-05-10T00:02:09.298+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:02:09.298+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_consumes_1 to None, run_after=None
[2024-05-10T00:02:09.318+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:02:09.317+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_consumes_1_and_2 to None, run_after=None
[2024-05-10T00:02:09.336+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:02:09.335+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_consumes_1_never_scheduled to None, run_after=None
[2024-05-10T00:02:09.450+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:02:09.447+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_consumes_unknown_never_scheduled to None, run_after=None
[2024-05-10T00:02:09.574+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:02:09.572+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_produces_1 to 2024-05-09 00:00:00+00:00, run_after=2024-05-10 00:00:00+00:00
[2024-05-10T00:02:09.596+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:02:09.595+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_produces_2 to None, run_after=None
[2024-05-10T00:02:10.131+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py took 1.123 seconds
[2024-05-10T00:02:40.393+0000] {processor.py:161} INFO - Started process (PID=25232) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py
[2024-05-10T00:02:40.396+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py for tasks to queue
[2024-05-10T00:02:40.398+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:02:40.398+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py
[2024-05-10T00:02:40.412+0000] {processor.py:840} INFO - DAG(s) 'dataset_consumes_1_and_2', 'consume_1_or_2_with_dataset_expressions', 'consume_1_and_2_with_dataset_expressions', 'dataset_consumes_1', 'dataset_produces_1', 'dataset_consumes_1_never_scheduled', 'consume_1_or_both_2_and_3_with_dataset_expressions', 'conditional_dataset_and_time_based_timetable', 'dataset_produces_2', 'dataset_consumes_unknown_never_scheduled' retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py
[2024-05-10T00:02:40.445+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:02:40.445+0000] {dag.py:3096} INFO - Sync 10 DAGs
[2024-05-10T00:02:40.465+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:02:40.465+0000] {dag.py:3954} INFO - Setting next_dagrun for conditional_dataset_and_time_based_timetable to 2024-05-08 01:00:00+00:00, run_after=2024-05-08 01:00:00+00:00
[2024-05-10T00:02:40.470+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:02:40.470+0000] {dag.py:3954} INFO - Setting next_dagrun for consume_1_and_2_with_dataset_expressions to None, run_after=None
[2024-05-10T00:02:40.472+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:02:40.472+0000] {dag.py:3954} INFO - Setting next_dagrun for consume_1_or_2_with_dataset_expressions to None, run_after=None
[2024-05-10T00:02:40.475+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:02:40.474+0000] {dag.py:3954} INFO - Setting next_dagrun for consume_1_or_both_2_and_3_with_dataset_expressions to None, run_after=None
[2024-05-10T00:02:40.476+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:02:40.476+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_consumes_1 to None, run_after=None
[2024-05-10T00:02:40.478+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:02:40.478+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_consumes_1_and_2 to None, run_after=None
[2024-05-10T00:02:40.480+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:02:40.480+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_consumes_1_never_scheduled to None, run_after=None
[2024-05-10T00:02:40.484+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:02:40.484+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_consumes_unknown_never_scheduled to None, run_after=None
[2024-05-10T00:02:40.486+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:02:40.486+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_produces_1 to 2024-05-09 00:00:00+00:00, run_after=2024-05-10 00:00:00+00:00
[2024-05-10T00:02:40.488+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:02:40.488+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_produces_2 to None, run_after=None
[2024-05-10T00:02:40.519+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py took 0.130 seconds
[2024-05-10T00:03:13.245+0000] {processor.py:161} INFO - Started process (PID=25289) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py
[2024-05-10T00:03:13.258+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py for tasks to queue
[2024-05-10T00:03:13.282+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:03:13.277+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py
[2024-05-10T00:03:13.334+0000] {processor.py:840} INFO - DAG(s) 'consume_1_or_2_with_dataset_expressions', 'dataset_consumes_1_never_scheduled', 'dataset_consumes_unknown_never_scheduled', 'consume_1_or_both_2_and_3_with_dataset_expressions', 'consume_1_and_2_with_dataset_expressions', 'dataset_consumes_1_and_2', 'conditional_dataset_and_time_based_timetable', 'dataset_consumes_1', 'dataset_produces_1', 'dataset_produces_2' retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py
[2024-05-10T00:03:13.490+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:03:13.489+0000] {dag.py:3096} INFO - Sync 10 DAGs
[2024-05-10T00:03:13.566+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:03:13.565+0000] {dag.py:3954} INFO - Setting next_dagrun for conditional_dataset_and_time_based_timetable to 2024-05-08 01:00:00+00:00, run_after=2024-05-08 01:00:00+00:00
[2024-05-10T00:03:13.618+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:03:13.616+0000] {dag.py:3954} INFO - Setting next_dagrun for consume_1_and_2_with_dataset_expressions to None, run_after=None
[2024-05-10T00:03:13.630+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:03:13.628+0000] {dag.py:3954} INFO - Setting next_dagrun for consume_1_or_2_with_dataset_expressions to None, run_after=None
[2024-05-10T00:03:13.649+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:03:13.646+0000] {dag.py:3954} INFO - Setting next_dagrun for consume_1_or_both_2_and_3_with_dataset_expressions to None, run_after=None
[2024-05-10T00:03:13.664+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:03:13.663+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_consumes_1 to None, run_after=None
[2024-05-10T00:03:14.276+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 497, in checkout
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    dbapi_connection = rec.get_connection()
                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 630, in get_connection
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "postgres" (172.18.0.3), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 859, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 895, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 664, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 677, in _sync_to_db
    _serialize_dag_capturing_errors(dag, session, processor_subdir)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 642, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/serialized_dag.py", line 158, in write_dag
    if session.scalar(
       ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 497, in checkout
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    dbapi_connection = rec.get_connection()
                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 630, in get_connection
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "postgres" (172.18.0.3), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-05-10T00:06:09.496+0000] {processor.py:161} INFO - Started process (PID=49) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py
[2024-05-10T00:06:09.525+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py for tasks to queue
[2024-05-10T00:06:09.548+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:06:09.545+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py
[2024-05-10T00:06:09.691+0000] {processor.py:840} INFO - DAG(s) 'dataset_consumes_1_and_2', 'conditional_dataset_and_time_based_timetable', 'dataset_produces_2', 'dataset_consumes_1', 'consume_1_or_both_2_and_3_with_dataset_expressions', 'consume_1_or_2_with_dataset_expressions', 'dataset_consumes_unknown_never_scheduled', 'consume_1_and_2_with_dataset_expressions', 'dataset_produces_1', 'dataset_consumes_1_never_scheduled' retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py
[2024-05-10T00:06:09.978+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:06:09.977+0000] {dag.py:3096} INFO - Sync 10 DAGs
[2024-05-10T00:06:10.092+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:06:10.092+0000] {dag.py:3954} INFO - Setting next_dagrun for conditional_dataset_and_time_based_timetable to 2024-05-08 01:00:00+00:00, run_after=2024-05-08 01:00:00+00:00
[2024-05-10T00:06:10.121+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:06:10.120+0000] {dag.py:3954} INFO - Setting next_dagrun for consume_1_and_2_with_dataset_expressions to None, run_after=None
[2024-05-10T00:06:10.153+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:06:10.151+0000] {dag.py:3954} INFO - Setting next_dagrun for consume_1_or_2_with_dataset_expressions to None, run_after=None
[2024-05-10T00:06:10.169+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:06:10.168+0000] {dag.py:3954} INFO - Setting next_dagrun for consume_1_or_both_2_and_3_with_dataset_expressions to None, run_after=None
[2024-05-10T00:06:10.187+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:06:10.186+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_consumes_1 to None, run_after=None
[2024-05-10T00:06:10.227+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:06:10.227+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_consumes_1_and_2 to None, run_after=None
[2024-05-10T00:06:10.253+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:06:10.252+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_consumes_1_never_scheduled to None, run_after=None
[2024-05-10T00:06:10.269+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:06:10.269+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_consumes_unknown_never_scheduled to None, run_after=None
[2024-05-10T00:06:10.290+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:06:10.288+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_produces_1 to 2024-05-09 00:00:00+00:00, run_after=2024-05-10 00:00:00+00:00
[2024-05-10T00:06:10.312+0000] {logging_mixin.py:188} INFO - [2024-05-10T00:06:10.312+0000] {dag.py:3954} INFO - Setting next_dagrun for dataset_produces_2 to None, run_after=None
[2024-05-10T00:06:10.472+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_datasets.py took 1.096 seconds
